/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PassInt */

#ifndef _Included_PassInt
#define _Included_PassInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PassInt
 * Method:    displayInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_PassInt_displayInt(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
