/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PassNativeTypes */

#ifndef _Included_PassNativeTypes
#define _Included_PassNativeTypes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PassNativeTypes
 * Method:    displayByte
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_PassNativeTypes_displayByte
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     PassNativeTypes
 * Method:    displayShort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_PassNativeTypes_displayShort
  (JNIEnv *, jclass, jshort);

/*
 * Class:     PassNativeTypes
 * Method:    displayInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_PassNativeTypes_displayInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     PassNativeTypes
 * Method:    displayLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PassNativeTypes_displayLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     PassNativeTypes
 * Method:    displayFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_PassNativeTypes_displayFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     PassNativeTypes
 * Method:    displayDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_PassNativeTypes_displayDouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     PassNativeTypes
 * Method:    displayBoolean
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_PassNativeTypes_displayBoolean
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     PassNativeTypes
 * Method:    displayChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_PassNativeTypes_displayChar
  (JNIEnv *, jclass, jchar);

#ifdef __cplusplus
}
#endif
#endif
