/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyClass */

#ifndef _Included_MyClass
#define _Included_MyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyClass
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyClass_accessField
  (JNIEnv *, jobject);

  JNIEXPORT void JNICALL Java_MyClass_accessStaticField
  (JNIEnv *, jobject);

   JNIEXPORT void JNICALL Java_MyClass_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
