/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIArrays */

#ifndef _Included_JNIArrays
#define _Included_JNIArrays
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIArrays
 * Method:    passBooleanArray
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_JNIArrays_passBooleanArray
  (JNIEnv *, jclass, jbooleanArray);

/*
 * Class:     JNIArrays
 * Method:    passByteArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_JNIArrays_passByteArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     JNIArrays
 * Method:    passCharArray
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_JNIArrays_passCharArray
  (JNIEnv *, jclass, jcharArray);

/*
 * Class:     JNIArrays
 * Method:    passShortArray
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_JNIArrays_passShortArray
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     JNIArrays
 * Method:    passIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_JNIArrays_passIntArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     JNIArrays
 * Method:    passLongArray
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_JNIArrays_passLongArray
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     JNIArrays
 * Method:    passFloatArray
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_JNIArrays_passFloatArray
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     JNIArrays
 * Method:    passDoubleArray
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_JNIArrays_passDoubleArray
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
