/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PassString */

#ifndef _Included_PassString
#define _Included_PassString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PassString
 * Method:    displayString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PassString_displayString
  (JNIEnv *, jclass, jstring);

JNIEXPORT jstring JNICALL Java_PassString_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
